name: CI Pipeline - Test, Build, Push (no Node)

on:
  push:
    branches: [ testing ]

env:
  REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}   # e.g. myacr.azurecr.io
  IMAGE_NAME: sit722-app
  IMAGE_TAG: ${{ github.sha }}
  IMAGE: ${{ secrets.ACR_LOGIN_SERVER }}/sit722-app:${{ github.sha }}
  PORT: 8080          
  PATH_CHECK: /health 

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build image (no push yet)
        uses: docker/build-push-action@v6
        with:
          context: ./backend/customer_service
          file: ./backend/customer_service/Dockerfile
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/sit722-app:${{ github.sha }}
          push: false
          load: true   # load to local Docker for smoke test
          cache-from: type=gha
          cache-to: type=gha,mode=max
     


      - name: Push image to ACR (only if tests passed)
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: ./backend/customer_service
          file: ./backend/customer_service/Dockerfile
          tags: ${{ env.IMAGE }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
