name: CI Pipeline - Test, Build, Push (no Node)

on:
  push:
    branches: [ testing ]

env:
  REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}   # e.g. myacr.azurecr.io
  IMAGE_NAME: sit722-app
  IMAGE_TAG: ${{ github.sha }}
  IMAGE: ${{ secrets.ACR_LOGIN_SERVER }}/sit722-app:${{ github.sha }}
  PORT: 8080          # change if your app uses a different port
  PATH_CHECK: /health # change if your app exposes another path

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build image (no push yet)
        uses: docker/build-push-action@v6
        with:
          context: ../../backend/customer_service/Dockerfile
          push: false
          tags: ${{ env.IMAGE }}
          load: true   # load to local Docker for smoke test

      - name: Smoke test container
        env:
          IMAGE: ${{ env.IMAGE }}
          PORT: ${{ env.PORT }}
          PATH_CHECK: ${{ env.PATH_CHECK }}
        run: ./.ci/smoke-test.sh

      - name: Push image to ACR (only if tests passed)
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}
