name: Deploy to Production

on:
  push:
    branches:
      - main

jobs: 
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Select subscription
        run: az account set --subscription e9880739-dae9-4c01-8b11-b828ed701da2
      - name: Deploy to production
        run: |
          az container create \
            --resource-group sit722-prod-rg \
            --name sit722-prod-app \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/sit722-app:${{ github.sha }} \
            --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --dns-name-label sit722-prod \
            --ports 80
